<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{1ccecfb9-0067-43da-b381-0c2544ecd532}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    {attribute 'pytmc' := '
        pv: TST:WFS:SPM
        io: i
    '}
    fb_pm: FB_PPM_PowerMeter;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_pm();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>