<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_MAIN" Id="{1ccecfb9-0067-43da-b381-0c2544ecd532}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_MAIN
VAR
    {attribute 'pytmc' := '
        pv: TST:WFS:SPM
        io: i
    '}
    fb_pm: FB_PPM_PowerMeter_DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_pm();
PRG_IM1_PPM();
PRG_IM2_PPM();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>